env_files = [{ path = "config/.env.dist.dev", profile = "development" }]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.check]
command = "cargo"
args = ["check", "${@}"]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]
