env_files = [
  { path = "config/.env.dist.dev", profile = "development" },
  { path = "config/.env.dist.ci", profile = "ci" },
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.check]
command = "cargo"
args = ["check", "${@}"]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]

[tasks.build]
command = "cargo"
args = ["build", "${@}"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]

[tasks.format-check]
description = "Runs the cargo rustfmt plugin during CI."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
