env_files = [
  { path = ".env", profile = "development" },
  { path = "config/.env.dist.ci", profile = "ci" },
]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.check]
command = "cargo"
args = ["check", "${@}"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]

[tasks.format-check]
description = "Runs the cargo rustfmt plugin during CI."
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
