name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: bitnami/redis:latest
        env:
          ALLOW_EMPTY_PASSWORD: yes
          REDIS_PORT_NUMBER: 6379
          REDIS_DATABASE: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install cargo make
        run: cargo install cargo-make
      - name: Clippy
        run: cargo make --profile ci clippy
      - name: Format
        run: cargo make --profile ci format-check
      - name: Run tests
        run: cargo make --profile ci test
