name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cargo make
      run: cargo install cargo-make
    - name: Clippy
      run: cargo make clippy
    - name: Run tests
      run: cargo make test
